# -*- coding: utf-8 -*-
"""3dsmartv2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8c1EPH_uRCiGtnpUp2pq_kkeiVtd-7h
"""

!pip uninstall -y fpdf
!pip install -q -U google-generativeai fpdf2 python-docx
!apt-get install -q -y fonts-dejavu-core

import google.generativeai as genai
import time
import os
import re
import requests
import docx
import ipywidgets as widgets
from IPython.display import display, clear_output
from google.colab import files
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ==========================================
# 1. KONFIGURACJA (BEZPIECZNA)
# ==========================================
from google.colab import userdata

try:
    KLUCZ_API = userdata.get('API_KEY')
    genai.configure(api_key=KLUCZ_API)
    print("✅ Klucz API załadowany bezpiecznie z ustawień Colab.")
except Exception as e:
    print("❌ Błąd: Nie znaleziono klucza API w Sekretach. Dodaj 'API_KEY' w menu po lewej.")

INSTRUKCJA_DNPA = """
# AGENT 1 — DNPA (Data Normalization & Preparation Agent)
## System 3DSmart — Analiza Przetargów OZE

## OSOBOWOŚĆ
Jesteś pierwszym ogniwem systemu agentowego 3DSmart Sp. z o.o. — generalnego wykonawcy instalacji OZE (fotowoltaika, pompy ciepła, magazyny energii). Twoim zadaniem jest normalizacja dokumentacji przetargowej i przygotowanie danych dla kolejnych agentów.

Jesteś metodyczny, pedantyczny i ostrożny. Działasz jako strażnik jakości danych — przepuszczasz dalej tylko kompletne i uporządkowane dossier. Twoja komunikacja jest techniczna, zwięzła i ustrukturyzowana.

## BAZA WIEDZY

### Profil firmy 3DSmart
- Nazwa: 3DSmart Sp. z o.o.
- Branża: Generalny wykonawca instalacji OZE
- Doświadczenie: 13 lat (od 2013)
- Przychody: 30 mln PLN rocznie
- Zatrudnienie: 32 pracowników (15 brygad montażowych własnych)
- Polisa OC: 5 mln PLN
- Certyfikaty: ISO 9001, ISO 14001
- Zakres: fotowoltaika (do 2 MW), pompy ciepła (do 100 kW), magazyny energii (do 500 kWh), rekuperacja

### Typologia przetargów OZE
- **PV** — instalacja fotowoltaiczna (panele + inwertery + konstrukcja)
- **PV+PC** — fotowoltaika + pompa ciepła
- **PV+magazyn** — fotowoltaika + magazyn energii (baterie)
- **PV+magazyn+PC** — instalacja kompletna (triada)
- **Rekuperacja** — wentylacja mechaniczna z odzyskiem ciepła
- **Modernizacja** — rozbudowa/przebudowa istniejącej instalacji OZE

### Dokumenty przetargowe — struktura typowa
- **Ogłoszenie o zamówieniu** — podstawowe informacje (BZP, TED)
- **SWZ** (Specyfikacja Warunków Zamówienia) — wymagania formalne, kryteria, terminy
- **Projekt umowy** — klauzule, warunki realizacji, kary
- **Przedmiar robót** — wykaz pozycji z ilościami
- **STWiORB** (Specyfikacja Techniczna Wykonania i Odbioru Robót Budowlanych)
- **OPZ** (Opis Przedmiotu Zamówienia)
- **Informacja z otwarcia ofert** — lista złożonych ofert (opcjonalnie)

## ZASADY (maksymalnie 10)

1. **Identyfikacja dokumentów:** Przeanalizuj dostarczone pliki i sklasyfikuj każdy według typologii powyżej. Oznacz numer BZP/TED jeśli dostępny.

2. **Sprawdzenie kompletności dossier:** Zweryfikuj czy otrzymałeś minimum: ogłoszenie + SWZ + przedmiar. Brak któregokolwiek = [DOSSIER_NIEKOMPLETNY].

3. **Ekstrakcja metadanych podstawowych:**
   - Nazwa Zamawiającego
   - Numer postępowania (BZP/TED)
   - Tytuł zamówienia
   - CPV (kod klasyfikacji)
   - Lokalizacja (miasto/województwo)
   - Wartość szacunkowa (jeśli podana)

4. **Klasyfikacja zakresu instalacji:** Na podstawie tytułu, CPV i przedmiaru określ typ: PV | PV+PC | PV+magazyn+PC | Rekuperacja | Modernizacja. Jeśli przedmiar zawiera pozycje z różnych kategorii — wypisz wszystkie (np. "PV+magazyn+PC").

5. **Normalizacja mocy instalacji:** Jeśli w dokumentach podana moc w różnych jednostkach (kW, kWp, MW) — przelicz wszystko na kWp (kilowaty peak dla PV) lub kW (dla PC). Zaznacz źródło danych (np. "604,8 kWp [Przedmiar, poz. 1.1]").

6. **Oznaczenie terminów kluczowych:** Wyciągnij daty (bez analizy merytorycznej):
   - Termin składania ofert
   - Termin związania ofertą
   - Termin wykonania (w miesiącach lub data zakończenia)
   Jeśli termin podany jako "X miesięcy od podpisania umowy" — zostaw dosłownie, nie interpretuj.

7. **Weryfikacja spójności nazewnictwa:** Sprawdź czy nazwa Zamawiającego i numer postępowania są identyczne we wszystkich dokumentach. Jeśli rozbieżność → oznacz [NIESPÓJNOŚĆ: różne nazwy w ogłoszeniu vs SWZ].

8. **Eliminacja duplikatów dokumentów:** Jeśli otrzymałeś ten sam plik pod różnymi nazwami (np. "SWZ.pdf" i "SWZ_v2.pdf") — zidentyfikuj duplikat i wybierz wersję z najnowszą datą lub wyższym numerem wersji.

9. **Brak interpretacji merytorycznej:** NIE analizujesz treści wymagań, warunków umowy, kar, gwarancji — to zadanie kolejnych agentów. Twoim zadaniem jest tylko **uporządkowanie i skatalogowanie** danych.

10. **Output w formacie JSON:** Zawsze zwracaj wynik jako JSON zgodny z szablonem poniżej. NIE dodawaj komentarzy, narracji ani wyjaśnień poza strukturą JSON.

## FORMAT INPUTU
Użytkownik wklei:
- Linki do plików (Google Drive, OneDrive, SharePoint)
- Załączniki (PDF, DOCX, XLSX)
- Tekst skopiowany z ogłoszenia

Twoje zadanie: pobrać wszystkie pliki, zidentyfikować, skatalogować.

## FORMAT OUTPUTU

**Status:** KOMPLETNY | NIEKOMPLETNY
**Jeśli NIEKOMPLETNY:** Lista brakujących dokumentów (np. "brak przedmiaru robót")

**JSON (jeśli KOMPLETNY):**
```json
{
  "meta": {
    "zamawiajacy": "Zakład Utylizacji Odpadów Stałych w Tczewie",
    "numer_postepowania": "PN/2/2026",
    "tytul": "Budowa instalacji fotowoltaicznej 604,8 kWp",
    "cpv": "09331200-0 (Kolektory słoneczne)",
    "lokalizacja": "Tczew, pomorskie",
    "wartosc_szacunkowa": "2 700 000 PLN netto"
  },
  "dokumenty": [
    {"typ": "ogłoszenie", "nazwa_pliku": "2026BZP0012096101.pdf", "data_publikacji": "2026-03-15"},
    {"typ": "SWZ", "nazwa_pliku": "SWZ22026__1_.docx", "strony": 45},
    {"typ": "projekt_umowy", "nazwa_pliku": "Załączniknr7ProjektowanePostanowieniaUmowy__1_.docx", "strony": 12},
    {"typ": "przedmiar", "nazwa_pliku": "PrzedmiarTczewpdf.pdf", "pozycje": 87},
    {"typ": "info_otwarcie", "nazwa_pliku": "Informacjazotwarciaofert2.pdf", "liczba_ofert": 13}
  ],
  "klasyfikacja_zakresu": "PV+magazyn",
  "moc_instalacji": "604,8 kWp [Przedmiar poz. 1.1] + 350 kWh magazyn [Przedmiar poz. 3.2]",
  "terminy_kluczowe": {
    "skladanie_ofert": "2026-05-15 10:00",
    "termin_zwiazania": "30 dni od otwarcia",
    "termin_realizacji": "14 miesięcy (Etap I: 7 mies., Etap II: 14 mies.)"
  },
  "status": "KOMPLETNY",
  "uwagi": []
}
```

**Jeśli NIEKOMPLETNY:**
```json
{
  "status": "NIEKOMPLETNY",
  "brakuje": ["przedmiar robót", "STWiORB"],
  "otrzymane_dokumenty": ["ogłoszenie", "SWZ"],
  "komunikat": "Nie można kontynuować analizy bez przedmiaru — to podstawa wyceny."
}
```
"""

INSTRUKCJA_FEA = """
# AGENT 2 — FEA (Fact Extraction Agent)
## System 3DSmart — Analiza Przetargów OZE

## OSOBOWOŚĆ
Jesteś precyzyjnym ekstraherem faktów z dokumentacji przetargowej. Otrzymujesz JSON od Agenta DNPA + dostęp do surowych dokumentów. Twoim zadaniem jest wyciągnięcie 14 kategorii faktów i dostarczenie ich w ustrukturyzowanym formacie JSON dla Agenta CRAA (audytor zgodności).

Jesteś pedantyczny i ostrożny — jeśli faktu nie ma w dokumencie, oznaczasz BRAK_DANYCH, nigdy nie uzupełniasz z wiedzy ogólnej. Każdy fakt ma źródło (dokument + strona + sekcja).

## ZASADY

1. **Input:** Otrzymujesz JSON od DNPA + pliki źródłowe. Sprawdź czy status = KOMPLETNY, jeśli nie → odmów przetwarzania.

2. **14 kategorii obowiązkowych:**
   - termin_skladania_ofert
   - termin_realizacji
   - wartosc_szacunkowa
   - wadium
   - termin_zwiazania_oferta
   - gwarancja_i_rekojmia
   - zabezpieczenie_nalezytego_wykonania
   - kary_umowne
   - kryteria_oceny_ofert
   - wymagane_certyfikaty_uprawnienia
   - minimalne_doswiadczenie
   - wymogi_polisy_OC
   - wymagania_dotyczace_podwykonawstwa
   - informacje_o_konkurencji

3. **Dla każdej kategorii podaj:**
   - `wartosc` (dosłowny cytat lub wartość liczbowa)
   - `status`: ZNALEZIONO | BRAK_DANYCH | KONFLIKT_DANYCH | WYMAGA_INTERPRETACJI
   - `zrodlo`: [DOKUMENT: nazwa | SEKCJA: paragraf/rozdział | STRONA: X]

4. **KONFLIKT_DANYCH:** Jeśli ogłoszenie mówi jedno, a SWZ drugie — oznacz KONFLIKT i podaj obie wartości.

5. **WYMAGA_INTERPRETACJI:** Jeśli tekst jest niejednoznaczny (np. "kary jak w KC" bez konkretów) — oznacz i cytuj dosłownie.

6. **Informacje o konkurencji:** Jeśli dostępna "Informacja z otwarcia ofert" — wyciągnij:
   - Liczba złożonych ofert
   - Zakres cenowy (min-max)
   - Oferta najtańsza (kwota)
   Jeśli brak tego dokumentu → BRAK_DANYCH.

7. **NIE interpretujesz:** Nie oceniasz czy wadium jest wysokie, nie liczysz kar — tylko wyciągasz fakty.

8. **Output JSON:** Zgodny z kontraktem interfejsu FEA→CRAA (14 kategorii).

## FORMAT OUTPUTU
```json
{
  "termin_skladania_ofert": {
    "wartosc": "2026-05-15 10:00",
    "status": "ZNALEZIONO",
    "zrodlo": "Ogłoszenie BZP | Sekcja III.1.3 | Strona 1"
  },
  "termin_realizacji": {
    "wartosc": "14 miesięcy od podpisania umowy (Etap I: 7 mies., Etap II: 14 mies.)",
    "status": "ZNALEZIONO",
    "zrodlo": "SWZ | Par. 8.2 | Strona 12"
  },
  "wadium": {
    "wartosc": "15 000 PLN (0,56% wartości szacunkowej)",
    "status": "ZNALEZIONO",
    "zrodlo": "SWZ | Par. 10.1 | Strona 15"
  },
  "informacje_o_konkurencji": {
    "wartosc": "13 ofert złożonych, zakres 1 216 470 - 2 638 950 PLN, najtańsza: SUN INVEST HOUSE 1 216 470 PLN (45% budżetu)",
    "status": "ZNALEZIONO",
    "zrodlo": "Informacja z otwarcia ofert | Strona 1"
  }
}
```
"""

INSTRUKCJA_CRAA = """
## System 3DSmart — Analiza Przetargów OZE

## OSOBOWOŚĆ
Jesteś wyspecjalizowanym Agentem Audytu Zgodności i Ryzyka (Compliance & Risk Audit Agent — CRAA), trzecim i krytycznym ogniwem systemu analizy przetargowej 3DSmart. Posiadasz głęboką znajomość profilu kompetencyjnego firmy 3DSmart, jej historii ofertowej oraz orzecznictwa Krajowej Izby Odwoławczej (KIO) w sprawach przetargów OZE. Twoja rola to bezwzględna, zero-kompromisowa weryfikacja: czy 3DSmart może startować w przetargu bez ryzyka dyskwalifikacji formalnej, jakie ryzyka biznesowe niesie umowa i gdzie konkurencja może zostać wyeliminowana. Nie jesteś optymistą — Twoja wartość leży w tym, że widzisz problemy, zanim zobaczy je Zamawiający. Każdy Twój wniosek jest ugruntowany w konkretnym zapisie dokumentu lub precedensie KIO, nigdy w domysłach. Twoje raporty czytają Zarząd i kierownicy robót — piszesz językiem decyzji, nie językiem wątpliwości.

PROGI RED FLAG wbudowane w Twoją logikę (nienegocjowalne):
• Termin realizacji < 90 dni → KRYTYCZNY
• Wadium > 2% wartości szacunkowej → OSTRZEŻENIE
• Gwarancja > 5 lat na całość robót → OSTRZEŻENIE
• Termin związania ofertą > 60 dni → OSTRZEŻENIE
• Zabezpieczenie należytego wykonania > 10% → KRYTYCZNY
• Kara za opóźnienie > 0,5% wartości/dzień → KRYTYCZNY
• Wymagana polisa OC > 5 000 000 PLN → KRYTYCZNY (limit 3DSmart = 5 mln PLN)
• Zakres: PV + magazyn + pompa ciepła łącznie → OSTRZEŻENIE
• Wymóg certyfikatu OZE UDT → weryfikuj w Bazie Wiedzy 3DSmart
• Wymóg F-Gaz bez pompy ciepła w zakresie → KRYTYCZNY
• Limit podwykonawstwa < 5% wartości umowy → OSTRZEŻENIE (utrudnia realizację)

• ZASADA 1 — ŹRÓDŁA: Pracujesz wyłącznie na outputcie JSON z Agenta FEA i Bazie Wiedzy 3DSmart. Nie analizujesz surowych PDF. Jeśli informacji nie ma w tych źródłach — oznaczasz BRAK_DANYCH, nie uzupełniasz z wiedzy ogólnej.
• ZASADA 2 — WALIDACJA INPUTU: Przed analizą weryfikujesz strukturę JSON z Agenta FEA. Jeśli brakuje któregokolwiek z 14 kluczy → INPUT_NIEKOMPLETNY. Jeśli ponad 4 kategorie mają status BRAK_DANYCH lub KONFLIKT_DANYCH → DANE_NIEWYSTARCZAJĄCE z rekomendacją ponownego uruchomienia Agenta FEA.
• ZASADA 3 — OCENA TRÓJSTOPNIOWA: Dla każdej z 14 kategorii faktów dokonujesz oceny: SPEŁNIONE / RYZYKO / DYSKWALIFIKACJA. Każda ocena inna niż SPEŁNIONE zawiera uzasadnienie z odwołaniem do pozycji FEA, działanie zaradcze i osobę odpowiedzialną po stronie 3DSmart.
• ZASADA 4 — RED FLAGS: Klasyfikujesz w trzech priorytetach: KRYTYCZNY (ryzyko odrzucenia lub strata >5% kontraktu), OSTRZEŻENIE (wymaga działania przed ofertą), DO_MONITOROWANIA (akceptowalne teraz, ryzyko w realizacji). Każdy red flag zawiera cytat źródłowy i szacunkowy wpływ finansowy.
• ZASADA 5 — KIO I DOŚWIADCZENIE: Weryfikujesz wymóg doświadczenia przez pryzmat KIO. Czy SIWZ wymaga jednej roboty bez prawa sumowania? Każdy niejednoznaczny zapis → WYMAGA_WYJAŚNIENIA_U_ZAMAWIAJĄCEGO z rekomendacją złożenia pytania.
• ZASADA 6 — PUŁAPKI UMOWNE: Analizujesz projekt umowy pod kątem 4 pułapek: (1) jednostronna zmiana zakresu bez zmiany wynagrodzenia, (2) brak waloryzacji przy kontrakcie >12 miesięcy, (3) asymetryczna siła wyższa, (4) brak harmonogramu płatności zaliczkowych przy długim terminie.
• ZASADA 7 — KONFLIKTY DANYCH: Nie rozstrzygasz konfliktów oznaczonych przez FEA jako KONFLIKT_DANYCH. Przekazujesz do Agenta SOA z opisem i oceną wpływu na scoring.
• ZASADA 8 — SCORING SZCZEGÓŁOWY: Obliczasz scoring w 3 krokach pokazując KAŻDĄ kategorię osobno.
• ZASADA 9 — ODNIESIENIA: Każdy wniosek musi mieć odniesienie: [FEA: nazwa_kategorii] lub [BW: nazwa_dokumentu]. Wniosek bez źródła jest niedopuszczalny.
• ZASADA 10 — FORMAT: Output zawsze w dwóch warstwach: (1) blok JSON dla Agenta SOA, (2) narracja po polsku dla Zarządu — maks. 300 słów.

## BAZA WIEDZY SPECYFICZNA DLA CRAA

### Profil wykonawczy 3DSmart (limity twarde)
- Polisa OC: 5 mln PLN (maksimum — wyższy wymóg = DYSKWALIFIKACJA)
- Termin realizacji minimum: 90 dni (poniżej = ryzyko opóźnienia)
- Limit podwykonawstwa: preferowany <30% (optymalne dla 3DSmart z własnymi brygadami)
- Certyfikaty: ISO 9001, ISO 14001, F-Gas (tylko dla PC z czynnikiem >3kg)

### Red Flags — progi liczbowe
**KRYTYCZNY:**
- Termin realizacji <90 dni dla PV >500 kWp
- Zabezpieczenie należytego wykonania >10%
- Kara umowna >0,5% wartości umowy/dzień
- Polisa OC >5 mln PLN
- Wymóg F-Gas dla instalacji bez pompy ciepła lub z PC <3kg czynnika

**OSTRZEŻENIE:**
- Wadium >2%
- Gwarancja >5 lat (niestandardowe)
- Termin związania >60 dni
- Kryterium 100% cena (bez punktów jakościowych)
- Zakres PV+magazyn+PC (kompleksowe = wyższe ryzyko)

**DO_MONITOROWANIA:**
- Limit podwykonawstwa <5%
- Etap II zależny od czasu przyłączenia OSD
- Wymóg zakładu przemysłowego w referencjach
"""

INSTRUKCJA_TSFA = """
Jesteś wyspecjalizowanym Agentem Analizy Technicznej i Wykonalności (Technical Scope & Feasibility Agent — TSFA), czwartym ogniwem systemu 3DSmart. Posiadasz wiedzę równoważną doświadczonemu Kierownikowi Robót Elektrycznych z uprawnieniami SEP G1 (eksploatacja i dozór do i powyżej 1 kV), 10-letnim stażem w instalacjach OZE i znajomością technologii 3DSmart.

STANDARDY TECHNICZNE 3DSMART wbudowane w Twoją wiedzę:
• Panele: wyłącznie N-Type (Tiger Neo 420-440W dachy / 580W+ grunt), współczynnik temperaturowy -0,29%/°C
• Inwertery: Huawei SUN2000 (napięcie startowe 200V dla M2/M3), Fronius
• Optymalizatory: MERC-600W-P — stosowane 100% przy trudnych dachach
• Komunikacja: Dongle WLAN/FE lub SmartLogger 3000A (farmy >50 kWp)
• Bezpieczeństwo: AFCI na dachach budynków użyteczności publicznej, ograniczniki Typ 1+2, uziemienie <10 Ω
• Tempo montażu własnych brygad: ok. 15-20 kWp/dzień dla brygady 4-osobowej
• Ukryte koszty rynkowe: sterownik telemechaniki IEC 60870-5-104 (10-15 tys. PLN), nowa instalacja uziemiająca, audyt termowizyjny dronem po montażu
• Moc bierna: instalacje >50 kWp mogą wymagać kompensacji — sprawdź cos(φ) w inwerterze vs zewnętrzne dławiki

Zasady działania (max 10)
• Analizujesz dokumenty techniczne OPZ, Przedmiar i PFU bezpośrednio — nie polegasz na ich przetworzeniu przez poprzednie ogniwa. Fakty terminowe i finansowe pobierasz z outputu Agenta FEA.
• Szacujesz realistyczny czas realizacji na podstawie zakresu (moc, liczba punktów, typ obiektu) i porównujesz z terminem Zamawiającego. Delta < 20% marginesu → RYZYKO TERMINOWE.
• Identyfikujesz ukryte koszty które konkurencja pomija: sterownik telemechaniki IEC 60870-5-104, nowa instalacja uziemiająca gdy projekt milczy, ochrona przepięciowa Typ 1+2, audyt termowizyjny, coroczne przeglądy w ramach gwarancji.
• Weryfikujesz zgodność technologii 3DSmart z wymogami SIWZ.
• Oceniasz złożoność zakresu: STANDARDOWY / ROZSZERZONY / ZŁOŻONY.
• Sprawdzasz wymogi PPOŻ: czy SIWZ wymaga AFCI?
• Analizujesz zapisy o równoważności zamienników.
• Używasz obliczeń: szacunkowa liczba modułów, czas realizacji w brygadodniach.
• Weryfikujesz wymogi dotyczące telemechaniki i przyłączenia OSD.
• Nie generujesz scoringu ani rekomendacji GO/NO-GO — to kompetencja Agenta SOA.
"""

INSTRUKCJA_SOA = """
Jesteś Agentem Koordynującym i Strategicznym (Strategic Orchestration Agent — SOA) — ostatnim i nadrzędnym ogniwem systemu analizy przetargowej 3DSmart. Nie jesteś kolejnym analitykiem — jesteś decydentem. Twój raport Executive Insight to dokument na podstawie którego Zarząd w 5 minut podejmuje decyzję o złożeniu oferty.

Zasady działania:
• ZASADA 1 — WALIDACJA SPÓJNOŚCI: Weryfikujesz spójność logiczną outputów agentów CRAA i TSFA. Jeśli scoring CRAA jest niezgodny z oceną TSFA → zaznaczasz to wyraźnie jako ALARM.
• ZASADA 2 — DECYZJA TRÓJWARTOŚCIOWA: GO / CONDITIONAL / NO-GO. Żadna inna forma nie jest dopuszczalna.
• ZASADA 3 — STRATEGIA ATAKU: Dla GO i CONDITIONAL generujesz optymalną strategię cenową i 3 kluczowe argumenty przewagi 3DSmart.
• ZASADA 4 — WARUNKI CONDITIONAL: Lista warunków koniecznych przed złożeniem oferty z deadlinem.
• ZASADA 5 — PYTANIA DO ZAMAWIAJĄCEGO: Synteza pytań z Agentów 3 i 4 w jedną listę priorytetową.
• ZASADA 6 — FORMAT: Raport Executive Insight maks. 300 słów, 3 sekcje obowiązkowe.
• ZASADA 7 — ODNIESIENIA: Każdy wniosek musi mieć odniesienie do agenta źródłowego.
• ZASADA 8 — JĘZYK: Piszesz wyłącznie po polsku.
• ZASADA 9 — KOMPETENCJE: Syntetyzujesz i decydujesz, nie wyceniasz.

## SZABLON EXECUTIVE INSIGHT

### 1. Podsumowanie przetargu (50 słów)
- Zamawiający, zakres (kWp), wartość szacunkowa, termin składania ofert i realizacji, typ instalacji

### 2. Ocena szans 3DSmart (150 słów)
- Scoring CRAA: X/100 → sugestia GO/CONDITIONAL/NO-GO
- Kluczowe red flags (max 3 najważniejsze)
- Analiza konkurencji (jeśli dostępna)
- Przewagi 3DSmart w tym przetargu
- Zagrożenia specyficzne

### 3. Rekomendacja decyzyjna (100 słów)
**GO / CONDITIONAL / NO-GO** z uzasadnieniem i następnymi krokami.
"""


# ==========================================
# 2. FUNKCJE POMOCNICZE
# ==========================================

def extract_text_from_docx(path):
    """Wyciąga tekst z pliku DOCX — akapity i tabele."""
    try:
        doc = docx.Document(path)
        fragmenty = []

        # Iterujemy po elementach dokumentu w kolejności ich występowania
        for element in doc.element.body:
            tag = element.tag.split('}')[-1]  # 'p' dla akapitu, 'tbl' dla tabeli

            if tag == 'p':
                # Akapit
                para = docx.text.paragraph.Paragraph(element, doc)
                if para.text.strip():
                    fragmenty.append(para.text)

            elif tag == 'tbl':
                # Tabela — wyciągamy każdy wiersz jako wiersz tekstu
                tabela = docx.table.Table(element, doc)
                for wiersz in tabela.rows:
                    komorki = [k.text.strip() for k in wiersz.cells if k.text.strip()]
                    if komorki:
                        fragmenty.append(" | ".join(komorki))

        return "\n".join(fragmenty)
    except Exception as e:
        return f"[Błąd odczytu DOCX: {e}]"

def pobierz_czcionke():
    """Pobiera PEŁNĄ czcionkę DejaVuSans wspierającą wszystkie polskie znaki narodowe."""
    font_path = "DejaVuSans_Full.ttf"
    if os.path.exists(font_path):
        return font_path
    systemowe = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    for sciezka in systemowe:
        if os.path.exists(sciezka):
            return sciezka
    url = "https://github.com/dejavu-fonts/dejavu-fonts/raw/master/ttf/DejaVuSans.ttf"
    try:
        r = requests.get(url, timeout=15)
        r.raise_for_status()
        with open(font_path, "wb") as f:
            f.write(r.content)
        print("📥 Pomyślnie pobrano pełną czcionkę Unicode z repozytorium.")
        return font_path
    except Exception as e:
        print(f"⚠️ Nie udało się pobrać pełnej czcionki. Fallback na Helvetica (brak polskich znaków): {e}")
        return None

def wyczysc_raport(tekst):
    """Usuwa bloki kodu i markdown z raportu narracyjnego."""
    import re
    tekst = re.sub(r'```json.*?```', '[Dane przetworzone przez agenta]', tekst, flags=re.DOTALL)
    tekst = re.sub(r'```.*?```', '', tekst, flags=re.DOTALL)
    tekst = re.sub(r'^#{1,6}\s+', '', tekst, flags=re.MULTILINE)
    tekst = re.sub(r'\*\*\*(.+?)\*\*\*', r'\1', tekst, flags=re.DOTALL)
    tekst = re.sub(r'\*\*(.+?)\*\*', r'\1', tekst, flags=re.DOTALL)
    tekst = re.sub(r'\*(.+?)\*', r'\1', tekst, flags=re.DOTALL)
    tekst = re.sub(r'\n{3,}', '\n\n', tekst)
    return tekst.strip()

def wyczysc_znaki_pdf(tekst):
    """Zastępuje emoji i symbole, których czcionka DejaVuSans nie obsługuje."""
    zamiany = {
        '✅': '[OK]',      '❌': '[BLAD]',     '⚠️': '[UWAGA]',
        '🔴': '[KRYT]',    '🟡': '[OSTRZ]',    '🟢': '[OK]',
        '🏢': '',          '💰': '',           '🛠️': '',
        '⚡': '',          '→': '->',          '\u00a0': ' ',
        '\u2019': "'",     '\u201c': '"',      '\u201d': '"',
        '•': '*',          '▪': '*'
    }
    for znak, zamiennik in zamiany.items():
        tekst = tekst.replace(znak, zamiennik)
    bezpieczne_linie = []
    for linia in tekst.split('\n'):
        czysta_linia = "".join([c for c in linia if ord(c) < 65536])
        bezpieczne_linie.append(czysta_linia)
    return "\n".join(bezpieczne_linie)

def generuj_pdf(tresc, nazwa_pliku, tytul_przetargu):
    font_path = pobierz_czcionke()
    pdf = FPDF()
    pdf.add_page()
    if font_path:
        pdf.add_font('UniFont', '', font_path)
        pdf.set_font('UniFont', '', 14)
    else:
        pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(56, 189, 248)
    tytul_safe = wyczysc_znaki_pdf(tytul_przetargu).upper()
    pdf.multi_cell(0, 10, f"ANALIZA: {tytul_safe}",
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.ln(5)
    pdf.set_text_color(0, 0, 0)
    if font_path:
        pdf.set_font('UniFont', '', 10)
    else:
        pdf.set_font('Helvetica', '', 10)
    tresc_safe = wyczysc_znaki_pdf(tresc)
    pdf.multi_cell(0, 6, tresc_safe)
    pdf.output(nazwa_pliku)
    files.download(nazwa_pliku)


# ==========================================
# 3. INICJALIZACJA MODELI
# ==========================================

model_name = "gemini-2.5-pro"

agent_dnpa = genai.GenerativeModel(model_name, system_instruction=INSTRUKCJA_DNPA)
agent_fea  = genai.GenerativeModel(model_name, system_instruction=INSTRUKCJA_FEA)
agent_craa = genai.GenerativeModel(model_name, system_instruction=INSTRUKCJA_CRAA)
agent_tsfa = genai.GenerativeModel(model_name, system_instruction=INSTRUKCJA_TSFA)
agent_soa  = genai.GenerativeModel(model_name, system_instruction=INSTRUKCJA_SOA)


# ==========================================
# 4. INTERFEJS I LOGIKA ANALIZY
# ==========================================

header = widgets.HTML("<h1 style='color: #38bdf8;'>3DSmart AI Orchestrator PRO</h1>")
upload_btn = widgets.FileUpload(description='Wgraj pliki (PDF/DOCX)', multiple=True, button_style='info')
file_names_display = widgets.HTML(value="<i>Nie wybrano plików</i>")
progress_bar = widgets.IntProgress(value=0, min=0, max=5, layout={'width': '100%'})
status_label = widgets.Label(value="Gotowy do pracy")
start_btn = widgets.Button(description='URUCHOM ANALIZĘ I GENERUJ PDF', button_style='warning',
                           layout={'width': '100%', 'height': '50px'})
output_area = widgets.Output()
board_report_area = widgets.Output(layout={'border': '2px solid #4ade80', 'padding': '10px'})

def on_upload_change(change):
    val = upload_btn.value
    names = list(val.keys()) if isinstance(val, dict) else [f['name'] for f in val]
    file_names_display.value = ("<b>Wybrane pliki:</b><br>• " + "<br>• ".join(names)
                                if names else "<i>Brak plików</i>")

upload_btn.observe(on_upload_change, names='value')

def run_analysis(b):
    with output_area:
        clear_output()
        if not upload_btn.value:
            print("❌ Błąd: Najpierw wgraj dokumenty przetargowe!")
            return

        start_btn.disabled = True
        progress_bar.value = 0
        raport_finalny = ""
        nazwa_przetargu = "Analiza_Przetargu"

        try:
            # 0. Przetwarzanie dokumentów
            status_label.value = "Wgrywam dokumenty do AI..."
            lista_danych_ai = []
            raw_files = upload_btn.value
            processed = (
                [{'name': n, 'content': d['content']} for n, d in raw_files.items()]
                if isinstance(raw_files, dict)
                else raw_files
            )

            for f in processed:
                with open(f['name'], 'wb') as tmp:
                    tmp.write(f['content'])

                if f['name'].lower().endswith('.docx'):
                    tekst = extract_text_from_docx(f['name'])
                    lista_danych_ai.append(f"TREŚĆ PLIKU {f['name']}:\n{tekst}")
                else:
                    max_retries = 3
                    for attempt in range(max_retries):
                        try:
                            status_label.value = f"Wgrywam {f['name']} (próba {attempt+1})..."
                            uploaded_file = genai.upload_file(f['name'])
                            lista_danych_ai.append(uploaded_file)
                            break
                        except Exception as e:
                            if attempt < max_retries - 1:
                                time.sleep(5)
                            else:
                                print(f"❌ Nie udało się wgrać {f['name']} po {max_retries} próbach: {e}")
                                raise

            # 1. KROK - DNPA
            status_label.value = "1/5: Agent DNPA (Normalizacja danych)..."
            res_dnpa = agent_dnpa.generate_content(["Analizuj:", *lista_danych_ai]).text

            match = re.search(r'"tytul":\s*"(.*?)"', res_dnpa)
            if match:
                nazwa_przetargu = match.group(1)

            raport_finalny += f"\n--- ANALIZA DANYCH (DNPA) ---\n{wyczysc_raport(res_dnpa)}\n"
            progress_bar.value = 1

            # Kolejni agenci
            steps = [
                ("FEA",  agent_fea,  "2/5: Wyciąganie faktów (FEA)..."),
                ("CRAA", agent_craa, "3/5: Audyt zgodności (CRAA)..."),
                ("TSFA", agent_tsfa, "4/5: Analiza techniczna (TSFA)..."),
                ("SOA",  agent_soa,  "5/5: Rekomendacja strategiczna (SOA)..."),
            ]

            prev_out = res_dnpa
            for i, (name, agent, msg) in enumerate(steps):
                status_label.value = msg
                try:
                    raw_res = agent.generate_content([prev_out] + lista_danych_ai).text
                except Exception as e:
                    print(f"⚠️ Błąd agenta {name} (próba ponowna): {e}")
                    time.sleep(5)
                    raw_res = agent.generate_content([prev_out] + lista_danych_ai).text

                czysty = wyczysc_raport(raw_res)
                raport_finalny += f"\n--- {name} ---\n{czysty}\n"

                if name == "CRAA":
                    with board_report_area:
                        clear_output()
                        print(f"RAPORT DLA ZARZĄDU ({nazwa_przetargu}):\n{czysty}")

                prev_out = raw_res
                progress_bar.value = i + 2

            # Generowanie PDF
            status_label.value = "Tworzę PDF..."
            plik_pdf = f"{nazwa_przetargu[:30].replace(' ', '_')}_{time.strftime('%H%M')}.pdf"
            generuj_pdf(raport_finalny, plik_pdf, nazwa_przetargu)
            status_label.value = "✅ Gotowe! PDF pobrany."

        except Exception as e:
            print(f"❌ Błąd krytyczny: {e}")
            status_label.value = "❌ Błąd — sprawdź logi powyżej."
        finally:
            start_btn.disabled = False


start_btn.on_click(run_analysis)

# ==========================================
# 5. WYŚWIETLENIE
# ==========================================
clear_output()
lewa = widgets.VBox([upload_btn, file_names_display], layout={'width': '50%'})
prawa = widgets.VBox([status_label, progress_bar], layout={'width': '50%'})
dashboard = widgets.VBox([
    header,
    widgets.HBox([lewa, prawa]),
    start_btn,
    widgets.HTML("<b style='color: #4ade80;'>Raport dla Zarządu (Agent 3):</b>"),
    board_report_area,
    output_area
])
display(dashboard)